### ISSUE TITLE
How to change the data_root variable in configs/datasets/diffusion-sorption.yaml and configs/datasets/navier-stokes.yaml

### ISSUE THREAD

**Issue by CHEN-si-yu** [ASK-Berkeley/physics-NNs-hard-constraints#1]
Hello developer, I did encounter an issue that requires modifying the data_root variable. Could you please provide specific instructions on how to modify this parameter to make it work locally? Thank you!

**Comment by nithinvc** [comment]
In order to change this variable, you just need to change the respective config files. The variable should point to a root folder with subdirectories splitting the data into train and test.

Specifically, modify these lines: [diffusion sorption](https://github.com/ASK-Berkeley/physics-NNs-hard-constraints/blob/main/configs/datasets/diffusion-sorption.yaml#L2) and [Navier stokes](https://github.com/ASK-Berkeley/physics-NNs-hard-constraints/blob/main/configs/datasets/navier-stokes.yaml#L2). Let me know if this resolves your issue.

**Comment by CHEN-si-yu** [comment]
Please forgive my limited understanding. Could you please tell me whether the dataset（such as "DatasetSplit.Train") is directly generated by the existing code in the project, or if it needs to be imported additionally? Alternatively, if it is convenient for you, I would greatly appreciate it if you could directly share the data files in data_root. My email is ：siyu-che22@mails.tsinghua.edu.cn.

**Comment by nithinvc** [comment]
No worries. "DatasetSplit.Train" is a sub-directory. I'll follow up via email for sharing the data.

**Comment by CHEN-si-yu** [comment]
Thank you very much for your help. I look forward to your response. Wishing you even greater success in the future.
